### PR TITLE
Replace most performance critical parts with data.table equivalents

### PR DESCRIPTION
**Pull request by fmannhardt**
* Initial grouping with min/max times is much faster in the simple case of no 'custom' attributes
* Fair speed-up of the lead caluclation also

Did not have time to do benchmarks, but improvement is quite clear.

### CODE REVIEW

**Comment by gertjanssenswillen** [comment]
NA timestamps seems a very exotic case to me. Don't think this justifies a lot of effort, we could just mention in the docs it's not really made for that.

**Comment by fmannhardt** [comment]
Could be nice for sequence data :-)

I will see if it is to much work I might just add a warning. Detecting NA should be relatively low overhead.

--
Felix

________________________________

**Comment by fmannhardt** [comment]
Ok, found the issue. The dplyr documentation for `dplyr::arrange` says:

> Missing values
> Unlike base sorting with sort(), NA are: always sorted to the end for local data, even when wrapped with desc().

In my case, by chance, this created the correct result. So, the solution is to simply warn when NAs are present.

**Comment by fmannhardt** [comment]
The code now warns users when there is an NA value in the timestamp.

**Comment by fmannhardt** [comment]
Just found that there is an upstream issue in Rdatatable/data.table#3381 that results in event logs with only one event being sorted incorrectly resulting in a process map with the End activity before the only real activity. Seems to be fixed in the next data.table version, so just noting this here.

**Pull request merged**
